version: 2
jobs:
  build:
    docker:
      - image: savoirfairelinux/odoo-ci:11.0
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo

    working_directory: /mnt/extra-addons

    steps:
      - checkout
      - run:
          name: Clone CRM
          command: git clone https://github.com/savoirfairelinux/crm && cd crm && git checkout 11.0 && cd ..

      - run:
          name: Clone Server Tools
          command: git clone https://github.com/OCA/server-tools  && cd server-tools && git checkout 11.0 && cd ..
 
      - run:
          name: Clone Web
          command: git clone https://github.com/OCA/web.git && cd web && git checkout 11.0 && cd ..

      - run:
          name: Clone Web Addons
          command: git clone https://github.com/savoirfairelinux/web-addons  && cd web-addons && git checkout 11.0 && cd ..

      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 5m

      - run:
          name: Odoo install base
          command: odoo --db_host=localhost --db_user=odoo --db_password=odoo -d circleci_test --workers=0 -i base --stop-after-init
      
      - run:
          name: MV auditlog
          command: mkdir auditlog && mv ./server-tools/auditlog/* ./auditlog
      
      - run:
          name: MV web
          command: mkdir web_widget_color && mv ./web/web_widget_color/* ./web_widget_color
     
      - run:
          name: MV web_timeline
          command: mkdir web_timeline && mv ./web/web_timeline/* ./web_timeline
          
      - run:
          name: MV web_widget_table
          command: mkdir web_widget_table && mv ./web-addons/web_widget_table/* ./web_widget_table     
      
      - run:
          name: Odoo install repos modules
          command: coverage run /usr/bin/odoo --db_host localhost --db_user odoo --db_password odoo -d circleci_test --workers=0 --test-enable -i $(find . -maxdepth 1 -type d ! -name '.*' -printf '%f,') --stop-after-init
